### PR TITLE
[CLEANUP] - Clearing Sonar-reported bugs

### PR DESCRIPTION
**Pull request by pamval**

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 3m with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|389|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/cde-plugin/job/PR-951/1/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 3m 32s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 5 test(s) failed:
- **org.pentaho.ctools.cde.impl.DashboardsImplTest.testGetDashboardFromPath**
```
    org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileDto
```
- **org.pentaho.ctools.cde.impl.DashboardsImplTest.testGetPath**
```
    org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileDto
```
- **org.pentaho.ctools.cde.impl.DashboardsImplTest.testGetFilterForCDEDashboardFiles**
```
    org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileDto
```
- **org.pentaho.ctools.cde.impl.DashboardsImplTest.testGetDashboardList**
```
    org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileDto
```
- **org.pentaho.ctools.cde.impl.DashboardsImplTest.testConstructor**
```
    org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileDto
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|389|5|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/cde-plugin/job/PR-951/2/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by pamval** [comment]
@pedrofvteixeira please review - Cleaning CDE of Sonar errors and warnings.

**Comment by pedrofvteixeira** [comment]
https://github.com/webdetails/cde/pull/951/checks?check_run_id=259332295

```
Bug A 0 Bugs
Vulnerability A 0 Vulnerabilities (and Security Hotspot 0 Security Hotspots to review)
Code Smell A 0 Code Smells
````

👍

**Pull request merged**
