### PR TITLE
[SP-6688] Backport of PPP-5167 - End-of-Life: AngularJS 1.8.0  Pentaho Data Integration - Move DET into a addon or a kar file (10.2 Suite)

### PR DESCRIPTION
**Pull request by davidmsantos90**
@webdetails/millenniumfalcon please review

Original Commits:
 - https://github.com/webdetails/cde/commit/13d02c1f2fb80cf0e7d933ee39258cfda95a694b
 - https://github.com/webdetails/cde/commit/2f459b4cd977a2fce4f530691db549f23e890e7c
 
❗ This PR needs to be squash & merge, to be a single commit and use the message in the PR title ❗ 

Merge together with https://github.com/pentaho/pentaho-det-ee/pull/697

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 3s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by mbrasil — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 1m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
:ok_hand: All tests passed!
 
Tests run: **397**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/cde-plugin/job/PR-1044/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
