### PR TITLE
[CDE-802] - Export Button gets wrong results when tables use input ht…

### PR DESCRIPTION
**Pull request by eliofreitas**
…ml tags other than filter's one

### CODE REVIEW

**Comment by eliofreitas** [comment]
Added a filter method to the find method so it only searches for the input with the type "search" and not just any input present in the table

**Comment by eliofreitas** [comment]
@pamval please review

**Comment by pamval** [comment]
unit tests?
Doesn't the require.js version of the component also need this fix ?

**Comment by eliofreitas** [comment]
@pamval updated please review

**Pull request merged**
