### PR TITLE
[CDE-875] - Making an editor only property layoutHeight, to have no d…

### PR DESCRIPTION
**Pull request by jvelasques**
…efault value

### CODE REVIEW

**Comment by jvelasques** [comment]
@pamval @afrjorge please review

**Comment by pamval** [comment]
Do old dashboards with the old property in the width/height continue working?
Both in layout items and charts?

**Comment by jvelasques** [comment]
@pamval yes, the charts use **height**, the layout elements will use **layoutHeight**
If a layout element has **height**, when the editor is populating the areas with the properties, it will detect this case, and switch it to **layoutHeight**, preventing the issue of having two Height properties which I was having in a previous version of my fix.
To render the old dashboards, the **DivRender** will still look for a **height** property, and if there's none, will check for a **layoutHeight** (the editor code ensures only one is present, favoring **layoutHeight**).

I haven't found layout elements using **width** so that one doesn't pose a problem

**Comment by pamval** [comment]
@afrjorge, please review

**Comment by jvelasques** [comment]
@pamval @afrjorge a note about this: if we edit or create a new dashboard after this fix, that dashboard will misbehave in previous versions of cde, due to the layout elements having **layoutHeight** instead of **height** (all the layout elements will be without height)

Wondering if we could have **layoutHeight** as an editor only property, making sure to replace it to **height** when saving... Since the default is the issue, this might work

**Pull request closed without merging**
